### ISSUE TITLE
README update request

### ISSUE THREAD

**Issue by sliu2013** [wavefrontHQ/wavefront-opentracing-sdk-csharp#2]
* Need to specify the required tags ("application", "service"). These 2 tags are required in order for users to use span-search qb in Wavefront
* If we can include the instruction about span extract/inject in the README, that will be great. Or the other way is to provide a URL link to the opentracing-sdk doc?!

**Comment by michael132** [comment]
https://github.com/wavefrontHQ/wavefront-sdk-csharp/blob/master/docs/apptags.md
